<?php

/**
 * @file
 * Various tweaks for site deminy.net.
 *
 * @author Demin Yin <deminy@deminy.net>
 */

/**
 * Implements hook_menu().
 */
function deminy_menu() {
  return array(
    'r4034blog' => array(
      'page callback'   => 'deminy_redirect',
      'access callback' => TRUE,
      'type'            => MENU_CALLBACK,
      'title'           => 'Access denied',
      'description'     => 'You are not authorized to access this page.',
    ),
  );
}

/**
 * Implements hook_theme().
 */
function deminy_theme() {
  return array(
    'deminy_denied' => array(
      'variables' => array(),
    ),
  );
}

/**
 * MENU_CALLBACK for /r4034blog.
 *
 * Redirect anonymous users from 403 Access Denied pages caused by old
 * Serendipity URLs indexed by Google to valid Drupal URLs if possible.
 */
function deminy_redirect() {
  if (array_key_exists('destination', $_GET)) {
    $path = $_GET['destination'];
    // Unset destination to avoid infinite loop for URL redirection.
    unset($_GET['destination']);

    if (stripos($path, 'blog/') === 0) {
      $path = ((stripos($path, 'blog/feeds/') === 0) ? 'sitemap.xml' : '<front>');
      // URL moved permanently.
      drupal_goto($path, array(), 301);
    }
  }

  // Display the default access denied page.
  return theme('deminy_denied');
}

/**
 * Display themed Access denied page.
 */
function theme_deminy_denied() {
  drupal_set_title(t('Access denied'));
  return t('You are not authorized to access this page.');
}

/**
 * Implements hook_form_alter().
 */
function deminy_form_alter(&$form, &$form_state, $form_id) {
  if (preg_match('/comment_node_(.+_)?form/', $form_id)
    || (('guestbook_form_entry_form' == $form_id)
      && !empty($form['display']['#value'])
      && ('link' != $form['display']['#value']))) {
    $msg = t('NOTE: Guest comments/posts may not be displayed immediately in case spam content detected.');

    if (empty($form['#prefix'])) {
      $form['#prefix'] = '';
    }
    $form['#prefix'] = '<p style="color:green">' . $msg . '</p>';
  }
}
